apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.jms.port }}
      targetPort: jms
      protocol: TCP
      name: jms
    - port: {{ .Values.service.mgmt.port }}
      targetPort: mgmt
      protocol: TCP
      name: mgmt
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
