consumer:
  environment:
    APP_QUEUE_RATE_AMOUNT: 3000
    APP_QUEUE_RATE_UNIT: Minutes
  keda:
    enabled: true
    query: "queue_length"
    threshold: 100
producer:
  environment:
    APP_QUEUE_BATCHSIZE: 10000
    APP_QUEUE_RATE_AMOUNT: 10000
    APP_QUEUE_RATE_UNIT: Minutes