consumer:
  replicaCount: 0
  fullnameOverride: consumer
  image:
    pullPolicy: Always
    tag: latest
  environment:
    SPRING_ACTIVEMQ_BROKERURL: tcp://queue:61616
  ingress:
    enabled: true
    hosts:
      - host: consumer.home.arpa
        paths:
          - path: /
            pathType: ImplementationSpecific
metrics:
  fullnameOverride: metrics
  image:
    pullPolicy: Always
    tag: latest
  environment:
    SPRING_ACTIVEMQ_BROKERURL: tcp://queue:61616
producer:
  fullnameOverride: producer
  image:
    pullPolicy: Always
    tag: latest
  environment:
    SPRING_ACTIVEMQ_BROKERURL: tcp://queue:61616
queue:
  fullnameOverride: queue
  ingress:
    enabled: true
    hosts:
      - host: queue.home.arpa
        paths:
          - path: /
            pathType: ImplementationSpecific
grafana:
  fullnameOverride: grafana
kube-prometheus:
  fullnameOverride: ""
  prometheus:
    ingress:
      enabled: true
      hostname: prometheus.home.arpa